version: '3'
x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '100k'
    max-file: '1'

networks:
    shared-services:
        external: true

services:
  mqtt-client-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: mqtt-client-server:1.0
    container_name: mqtt-client-server
    logging: *default-logging
    networks:
      - shared-services

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432